game:
  queue:
    name: game-queue
  exchange:
    name: game-queue
server:
  port: 9092
spring:
  application:
    name: player-2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  level:
    app: debug
