game:
  queue:
    name: game-of-three
  exchange:
    name: game-of-three
server:
  port: 9092
spring:
  application:
    name: player-2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
